cd G:\Projects\iom_cars\scrapers
G:
athol.py
bcc_cars.py
bespokegroup.py
best_cars.py
bettridges.py
brentmealin.py
bvsvehicles.py
dwcars.py
franklins.py
ingear_carsales.py
jacksons.py
kingswood_honda.py
manx_carstore.py
mikes_motors.py
mike_hewison.py
motor_mall.py
mylchreests.py
oceanford.py
paulridgway_iom.py
philshawvehicles.py
signature_car_sales.py
sncc.py
swift_motors.py
td_car.py
@pause